// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: customers.sql

package datastore

import (
	"context"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
  id,
  username
) VALUES (
  $1, $2
) RETURNING id, username
`

type CreateCustomerParams struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer, arg.ID, arg.Username)
	var i Customer
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}
